Repository keshav1245/apratim2019, pull requests merged in 2019-10, with the labels that each got.

#12 street play,short movie
  Streetplay.html
  events/Shortmovie.html
  images/film.jpg
  index.html
Labels: Review Needed

#13 Fusion Band and Mime Web Page
  events/fusionBand.html
  events/mime.html
  images/fusion.jpg
  images/mime1.jpg
  index.html
Labels: Review Needed

#14 create kbc.html
  events/kbc.html
Labels: Ready to Merge

#16 update index.html
  index.html
Labels: Review Needed

#22 Robo Soccer and botpull webpage
  events/botpull.html
  events/website.html
  images/botpull2.jpg
  images/robosoccer1.jpg
  images/robosoccer2.jpg
  index.html
Labels: Review Needed

#21 Add files via upload
  images/kbc.jpg
  images/tech-hunt.jpg
Labels: Review Needed

#20 update index.html
  index.html
Labels: Review Needed

#19 create tech-hunt.html
  events/tech-hunt.html
Labels: Review Needed

#17 Add files via upload
  events/duet_dance.html
  events/group_dance.html
  images/duet.jpg
  images/group.jpg
  index.html
  style.css
Labels: Changes Made Needs Second Review

#18 Add files via upload
  events/code-in-the-dark.html
  events/codingrelay.html
  events/ui-design.html
  images/codeinthedark.jpg
Labels: Ready to Merge

#48 TITLE CHANGED + REGISTRATION LINK
  events/fusionBand.html
  events/mime.html
  events/monoact.html
Labels: Review Needed

#47 FIFA , PUBG AND CSGO WEBPAGE UNDER LAN GAMING
  events/CounterStrike.html
  events/Pubg.html
  events/fifa.html
  images/Pubg.jpg
  images/csgo.jpg
  images/csgo2.jpg
  images/fifa.jpg
  index.html
Labels: Review Needed

#80 Added Titles and Links to event pages.
  events/AquaJet.html
  events/CAD Modelling
  events/CADmodelling.html
  events/CounterStrike.html
  events/JAM.html
  events/Pubg.html
  events/Quiz.html
  events/Shortmovie.html
  events/Streetplay.html
  events/admad.html
  events/bhangrawars.html
  events/bob-the-builder.html
  events/botpull.html
  events/bridge_it.html
  events/code-in-the-dark.html
  events/codingrelay.html
  events/conv-debate.html
  events/duet_dance.html
  events/fashionShow.html
  events/fifa.html
  events/folkdance.html
  events/fusionBand.html
  events/group-dance.html
  events/group-discussion.html
  events/group_dance.html
  events/highq.html
  events/kbc.html
  events/line-follower.html
  events/mime.html
  events/monoact.html
  events/others.html
  events/quiz-mania.html
  events/roborace.html
  events/solodance.html
  events/soloinstrumental.html
  events/solosinging.html
  events/tech-hunt.html
  events/technobrain.html
  events/terribletales.html
  events/town-planning.html
  events/ui-design.html
  events/website.html
  index.html
Labels: Review Needed
